services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: natural-disasters-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
